// import Input from '@/app/_components/input'
// import React, { useState } from 'react'
// import { Plus, User, Home, MapPin, Hash, Users } from 'lucide-react';
// export default function AddressSection() {
//     const [errors, setErrors] = useState({});
//     const handleInputChange = (e) => {
//         const { name, value, type, checked } = e.target;
//         setFormData(prev => ({
//             ...prev,
//             [name]: type === 'checkbox' ? checked : value
//         }));
//     };
//     const [formData, setFormData] = useState({
//         familyNumber: '',
//         isAutoGenerated: true,
//         headOfFamily: '',
//         isExistingResident: true,
//         sitio: '',
//         street: '',
//         houseNumber: '',
//         ownershipType: ''
//     });
//     return (
//         <div>
//             <div>
//                 <label className="block text-sm font-medium text-gray-700 mb-3">
//                     <MapPin className="inline w-4 h-4 mr-1" />
//                     Address *
//                 </label>

//                 <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
//                     <Input
//                         label="Sitio"
//                         name="sitio"
//                         value={formData.sitio}
//                         onChange={handleInputChange}
//                         iconLeft={<MapPin className="w-4 h-4" />}
//                         error={errors.sitio}
//                         required
//                     />
//                     <Input
//                         label="Street"
//                         name="street"
//                         value={formData.street}
//                         onChange={handleInputChange}
//                     />
//                     <Input
//                         label="House Number"
//                         name="houseNumber"
//                         value={formData.houseNumber}
//                         onChange={handleInputChange}
//                     />
//                 </div>
//             </div>
//         </div>
//     )
// }
