// import Input from '@/app/_components/input'
// import React, { useState } from 'react'
// import { Plus, User, Home, MapPin, Hash, Users } from 'lucide-react';
// import moment from 'moment';
// export default function FamHoldSection() {
//   const [errors, setErrors] = useState({});
//    const [formData, setFormData] = useState({
//       familyNumber: '',
//       isAutoGenerated: true,
//       headOfFamily: '',
//       isExistingResident: true,
//       sitio: '',
//       street: '',
//       houseNumber: '',
//       ownershipType: ''
//     });
 
//   const handleAutoGenerateToggle = (e) => {
//     const isAuto = e.target.checked;
//     setFormData(prev => ({
//       ...prev,
//       isAutoGenerated: isAuto,
//       familyNumber: isAuto ? 'FAM-'+moment().format('MMDDYYHHmmss') : ''
//     }));
//   };
//   const handleInputChange = (e) => {
//     const { name, value, type, checked } = e.target;
//     setFormData(prev => ({
//       ...prev,
//       [name]: type === 'checkbox' ? checked : value
//     }));
//   };
//   return (

//     <div>
//        <label className="block text-sm font-medium text-gray-700 mb-3">
//             Family/Household Number *
//           </label>
//           <div className="space-y-3">
//             <div className="flex items-center gap-3">
//               <Input
//                 type="checkbox"
//                 id="autoGenerate"
//                 checked={formData.isAutoGenerated}
//                 onChange={handleAutoGenerateToggle}
//                 className="w-4 h-4 text-green-600 border-gray-300 rounded focus:ring-green-500"
//               />
//               <label htmlFor="autoGenerate" className="text-sm text-gray-700">
//                 Auto-generate family number
//               </label>
//             </div>

//             <Input
//               label="Family/Household Number"
//               name="familyNumber"
//               value={formData.familyNumber}
//               onChange={handleInputChange}
//               disabled={formData.isAutoGenerated}
//               iconLeft={<Hash className="w-4 h-4" />}
//               error={errors.familyNumber}
//               readOnly={formData.isAutoGenerated}
//             />
//           </div> 
//     </div>
//   )
// }

