// import React, { useState } from 'react'
// import { Plus, User, Home, MapPin, Hash, Users } from 'lucide-react';
// export default function OwnershipSection() {
//     const [errors, setErrors] = useState({});
//     const handleInputChange = (e) => {
//         const { name, value, type, checked } = e.target;
//         setFormData(prev => ({
//             ...prev,
//             [name]: type === 'checkbox' ? checked : value
//         }));
//     }
//     const [formData, setFormData] = useState({
//         familyNumber: '',
//         isAutoGenerated: true,
//         headOfFamily: '',
//         isExistingResident: true,
//         sitio: '',
//         street: '',
//         houseNumber: '',
//         ownershipType: ''
//     });
//     const ownershipTypes = [
//         "Owned",
//         "Rented",
//         "Government Housing",
//         "Caretaker",
//         "Sharing/Boarding",
//         "Others"
//     ];
//     return (
//         <div>
//             <div>
//                 <label className="block text-sm font-medium text-gray-700 mb-3">
//                     <Home className="inline w-4 h-4 mr-1" />
//                     Ownership Type *
//                 </label>

//                 <div className="relative">
//                     <Home className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4 z-10" />
//                     <select
//                         name="ownershipType"
//                         value={formData.ownershipType}
//                         onChange={handleInputChange}
//                         className="w-full pl-10 pr-4 py-2.5 border bg-white rounded-md focus:outline-none"
//                     >
//                         <option value="">Select ownership type</option>
//                         {ownershipTypes.map(type => (
//                             <option key={type} value={type}>{type}</option>
//                         ))}
//                     </select>
//                     {errors.ownershipType && <p className="text-sm text-red-500 mt-1 ml-1">{errors.ownershipType}</p>}
//                 </div>
//             </div>
//         </div>
//     )
// }
