<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Families extends Model
{
    protected $fillable = [


      
        'familyNumber',
        'isAutoGenerated',
        'headOfFamily',
        'isExistingResident',
        'sitio',
        'street',
        'houseNumber',
        'ownershipType',

    ];
}
